### ISSUE TITLE
config.json for python examples

### ISSUE THREAD

**Issue by nayakned** [GENIVI/iot-event-analytics#31]
Looks like the config.json files for python examples is outdated or inconsistent with what the platform software is expecting.

Trying to get the platform containers up using docker-compose fails with the config for the python examples (output below).
```
Error: Path protocolGateway does not exist
docker-compose_pipeline_1 exited with code 1
docker-compose_configmanager_1 exited with code 1
```

config.json (https://github.com/GENIVI/iot-event-analytics/blob/develop/src/sdk/python/examples/basic/config/config.json & https://github.com/GENIVI/iot-event-analytics/blob/develop/src/sdk/python/examples/remote/config/config.json) do not include the following paths
```
"protocolGateway": {
    "adapters": [
            {
                "platform": true,
                "module": {
                    "name": "./util/mqttClient",
                    "class": "MqttProtocolAdapter"
                },
                "config": {
                    "topicNamespace": "iotea/",
                    "mqtt5Only": true,
                    "brokerUrl": "mqtt://mosquitto:1883"
                }
            }
        ]
    },

```

**Comment by llakie** [comment]
Thank you for the hint. This will be fixed in version 0.4.0 of the python SDK. #33
