### ISSUE TITLE
VS Code plugin require specific versions for tools e.g. Docker

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#34]
It would be helpful to state the required tool versions e.g. for Docker either in the documentation e.g. [https://github.com/GENIVI/iot-event-analytics/tree/develop/src/sdk/vscode] or in the running plug-in.

**Comment by llakie** [comment]
Thanks for the hint. Will be re-added to the requirements section of the extension documentation. Fixed in #33
