### ISSUE TITLE
Can't select .env file on MAC OS

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#35]
The VSIX environment file selector does not work (also if hidden files are visible) on MAC OS. A viable solution is to remove the filter in the method "chooseComposeEnvFile".

**Comment by llakie** [comment]
I disagree on that point. We should stick to the file filtering but make it work on macOS. I might have something to do with the fact, that hidden files are not displayed. We added a troubleshooting entry for this in the README.md in the `bugfix/dot-env-files-on-macos`. Please follow this simple step and check out if the .env shows up in the selection
