### ISSUE TITLE
Docker Compose and proxy settings

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#36]
The usage of DOCKER_HTTP_PROXY and DOCKER_HTTPS_PROXY environment variable e.g. in docker compose file .env is not helpful. If the environment variable is not set, the build fails. If set and no proxy is available, the build also fails. The only way of getting it running (on MAC OS) is to drop it from the docker compose .env file and use docker command-line parameters.

**Comment by llakie** [comment]
This will potentially be fixed in the 0.4.0 release. Both settings were removed from the default .env file
