### ISSUE TITLE
Visual Studio Code Plugin (VSIX) and MAC OS shortcuts

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#37]
Would it be possible to have environment specific keyboard shortcut descriptions? The given one help for Windows and Linux, but not for MAC OS.

**Comment by llakie** [comment]
Command palette invocation shortcut for macOS will be added in feature/#37

**Comment by SebastianSchildt** [comment]
At @BDUG  are the docs correct now?

**Comment by llakie** [comment]
Closed due to inactivity
