### ISSUE TITLE
Unclear warnings while starting the platform - "broker is offline"

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#39]
While starting the platform sometimes (often in the early start-up phase) the message "MQTT Broker .... is offline. Cannot publish message to..."

**Comment by llakie** [comment]
This is actually just an info, that the underlying MQTT Client is not connected to the broker yet.
This should be fixed in version 0.4.0

**Comment by SebastianSchildt** [comment]
Did 0.40 solve this?

**Comment by llakie** [comment]
We decreased the loglevel of these messages. So they should actually be gone, if the platform loglevel is set appropriately.

**Comment by llakie** [comment]
Due to inactivity this issue will be closed.
