### ISSUE TITLE
Platform namespace is missing in some examples and in documentation

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#40]
In most SDK example the MQTT topic namespace is not set and not well documented. At least in the basic Javascript example the line process.env.MQTT_TOPICS_NS = 'iotea/' is needed.

**Comment by llakie** [comment]
In the JS-SDK and in the platform, the namespace is defined in the configuration of the Gateway protocol adapter. The environment option is not supported anymore and is deprecated, thus removed from the examples
