### ISSUE TITLE
More expressiv documentation on Protocol Adapter

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#43]
Many thanks for the nice example on hooking in an an adapter with different configuration: https://github.com/GENIVI/iot-event-analytics/tree/0.3.0/src/sdk/javascript/examples/protocols . May is it possible to give an documentation on how own "protocol adapters" could be written e.g. for plugging in specific hardware sensors and/or actuators, bridging to other middleware's.

**Comment by llakie** [comment]
Will be fixed in  PR #97. Can be found in _docs/topics/iotea-protocol-gateway.md_

**Comment by llakie** [comment]
Merged
