### ISSUE TITLE
CPP workflow not set up/triggered correctly?

### ISSUE THREAD

**Issue by SebastianSchildt** [GENIVI/iot-event-analytics#49]
I merged #48 , is there anything that needs to be checked in the repo?

I saw the badge empty and pointing to https://github.com/GENIVI/iot-event-analytics/actions/workflows/build_cpp_sdk_cmake.yml  "workflow does not exist"; but I do see it here https://github.com/GENIVI/iot-event-analytics/tree/develop/.github/workflows

Any ideas? Never used GH Actions....
@argerus  ( I can not seem to assign you, but you may have the best idea, what is going on 😸    )

**Comment by argerus** [comment]
This was _drive-by_ fixed in PR #51
