### ISSUE TITLE
Compatible with new kuksa.val version 0.1.9

### ISSUE THREAD

**Issue by wenwenchenbosch** [GENIVI/iot-event-analytics#71]
After I update the kuksa.val version to the new released version [0.1.9](https://github.com/eclipse/kuksa.val/releases/tag/0.1.9) in the following .env file:

https://github.com/GENIVI/iot-event-analytics/blob/0dd7f180ea9f703ae2bcdab70bc071536d86f59c/src/sdk/javascript/examples/integrations/kuksa.val/.env#L4

The VssWorker talent does not work properly. `kuksa.val` can still receive the published signal `Vehicle.Acceleration.Vertical`, but other talent can not receive events for the feature `Acceleration$Longitudinal` with type `Vehicle` any more. No error message seen in the log.

I think this happens after the PR https://github.com/eclipse/kuksa.val/pull/185 for the issue https://github.com/eclipse/kuksa.val/issues/160. Because using [kuksa-val:28117eb](https://github.com/eclipse/kuksa.val/tree/28117eb86c67807d3dafd49c7772abc178dbb8d8), it works, but not with the new version any more.

**Comment by wenwenchenbosch** [comment]
@SebastianSchildt @nayakned fyi

**Comment by llakie** [comment]
We will update the image reference in the given example to the newest release.

**Comment by llakie** [comment]
Will be fixed in #99
