### ISSUE TITLE
Documentation is outdated for building the JS library

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#82]
On the start page it is mentioned that the command `yarn` should be enough to get everything build. In my experience the command is `yarn sdk.build`. In some sub documentations the command is stated as `yarn build.sdk`. IMHO the README.md should be updated.

**Comment by llakie** [comment]
Yes, you are right. Since we removed the postinstall script for creating the SDKs automatically, we have to add this to the manual to make the SDK selection in the VSCode Extension working. Thanks for the hint

**Comment by llakie** [comment]
Will be fixed in  PR #97

**Comment by llakie** [comment]
Merged
