### ISSUE TITLE
Shortcut for MS Visual Studio code should be extended for MAC OS

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#83]
The shortcut strg+space notwork on all MAC.OS versions, but option+esc is a good alternative on MAC OS.

**Comment by llakie** [comment]
You are referring to the autocomplete commands in the VSCode Extension documentation, right?

**Comment by llakie** [comment]
Will be fixed in  PR #97

**Comment by llakie** [comment]
Merged
