### ISSUE TITLE
Visual Studio Code snippets not installed correctly

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#84]
On my machine the file `talent.demo.js` is placed in a wrong directory. This results in failed JS talent creation.

**Comment by llakie** [comment]
Could you please give us more information about the actual and the expected directory to make it easier for us to track down the issue?

**Comment by llakie** [comment]
I tried to recreate the bug, but I did not succeed. If I create a project, the `talent.demo.js` is copied into my project folder and renamed to `index.js`. Maybe you thought it should keep its name and that was the issue. Can you please quote?

**Comment by llakie** [comment]
Closed, since it could not be reproduced
