### ISSUE TITLE
tldr seems to require prerequisites

### ISSUE THREAD

**Issue by PhilippMundhenk** [GENIVI/iot-event-analytics#87]
I started with the promisingly named tldr section, to get it run asap. It seems this does require the prerequisites though. A note on that would be helpful. that section is "too long, didn't read" (tldr).

**Comment by llakie** [comment]
Good hint. I will add this as the first line in the tldr section. The intention was, that this section is read, after the prerequisites section has been read ;)

**Comment by llakie** [comment]
Will be fixed in  PR #97

**Comment by llakie** [comment]
Merged
